version: 2
name: pcm1环境cicd
description: ""
global:
  concurrent: 1
trigger:
  webhook: gitlink@1.0.0
  event:
    - ref: create_tag
      ruleset:
        - param-ref: tag
          operator: EQ
          value: '"部署"'
      ruleset-operator: AND
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: ssh_cmd_0
    name: ssh执行命令
    task: ssh_cmd@1.1.0
    input:
      ssh_private_key: ((SSH.pcm1))
      ssh_ip: '"123.60.146.162"'
      ssh_port: '"22"'
      ssh_user: '"pcm"'
      ssh_cmd: '"
        cd /home/pcm/deploy/cloudream/workspace/storage_yml
        &&
        sh 1_pull.sh
        &&
        ls /usr/local/go/bin
        &&
        echo PATH1:$PATH
        &&
        export PATH=$PATH:/usr/local/go/bin
        &&
        echo PATH2:$PATH
        &&
        sh 2_build_all.sh
        &&
        sudo sh 3_deploy.sh "'
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - ssh_cmd_0