version: 2
name: 基于gitlink构建
description: ""
global:
  concurrent: 1
  cache:
    - GOCACHE
    - GOMODCACHE
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.9
    input:
      username: ((gitlink.songjc))
      password: ((gitlink.songjc))
      remote_url: '"https://gitlink.org.cn/JointCloud/storage.git"'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 1
    needs:
      - start
  - ref: docker_image_build_2
    name: scanner镜像构建
    task: docker_image_build@1.6.0
    input:
      docker_username: ((docker_registry.registry_user))
      docker_password: ((docker_registry.registry_password))
      image_name: '"112.95.163.90:5010/scannerservice-x86"'
      image_tag: '"latest"'
      registry_address: '"123.60.146.162:5010"'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: docker_image_build_1
    name: coor镜像构建
    task: docker_image_build@1.6.0
    input:
      docker_username: ((docker_registry.registry_user))
      docker_password: ((docker_registry.registry_password))
      image_name: '"112.95.163.90:5010/coordinatorservice-x86"'
      image_tag: '"latest"'
      registry_address: '"123.60.146.162:5010"'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: docker_image_build_3
    name: client镜像构建
    task: docker_image_build@1.6.0
    input:
      docker_username: ((docker_registry.registry_user))
      docker_password: ((docker_registry.registry_password))
      image_name: '"112.95.163.90:5010/clientservice-x86"'
      image_tag: '"latest"'
      registry_address: '"123.60.146.162:5010"'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: ssh_cmd_0
    name: ssh执行命令
    task: ssh_cmd@1.1.1
    input:
      ssh_ip: '""'
      ssh_port: '"22"'
      ssh_user: '"root"'
      ssh_cmd: '""'
    needs:
      - docker_image_build_2
      - docker_image_build_0
      - docker_image_build_1
      - docker_image_build_3
  - ref: end
    name: 结束
    task: end
    needs:
      - ssh_cmd_0
  - ref: docker_image_build_0
    name: agent镜像构建
    task: docker_image_build@1.6.0
    input:
      docker_username: ((docker_registry.registry_user))
      docker_password: ((docker_registry.registry_password))
      image_name: '"112.95.163.90:5010/agentservice-x86"'
      image_tag: '"latest"'
      registry_address: '"123.60.146.162:5010"'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0

