version: 2
name: 未命名项目
description: ""
global:
  concurrent: 1
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: ssh_cmd_0
    name: ssh执行命令
    task: ssh_cmd@1.1.1
    input:
      ssh_pass: ((SSH.pcm1))
      ssh_ip: '"123.60.146.162"'
      ssh_port: '"22"'
      ssh_user: '"pcm"'
      ssh_cmd: '"ls /home/pcm/deploy/cloudream/workspace/storage_yml"'
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - ssh_cmd_0

