version: 2
name: 未命名项目
description: ""
global:
  concurrent: 1
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.9
    input:
      remote_url: '""'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 1
    needs:
      - start
  - ref: docker_image_build_2
    name: docker镜像构建
    task: docker_image_build@1.6.0
    input:
      image_name: '""'
      image_tag: '"latest"'
      registry_address: '""'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: docker_image_build_1
    name: docker镜像构建
    task: docker_image_build@1.6.0
    input:
      image_name: '""'
      image_tag: '"latest"'
      registry_address: '""'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: docker_image_build_3
    name: docker镜像构建
    task: docker_image_build@1.6.0
    input:
      image_name: '""'
      image_tag: '"latest"'
      registry_address: '""'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: ssh_cmd_0
    name: ssh执行命令
    task: ssh_cmd@1.1.1
    input:
      ssh_ip: '""'
      ssh_port: '"22"'
      ssh_user: '"root"'
      ssh_cmd: '""'
    needs:
      - docker_image_build_2
      - docker_image_build_0
      - docker_image_build_1
      - docker_image_build_3
      - docker_image_build_4
  - ref: end
    name: 结束
    task: end
    needs:
      - ssh_cmd_0
  - ref: docker_image_build_4
    name: docker镜像构建
    task: docker_image_build@1.6.0
    input:
      image_name: '""'
      image_tag: '"latest"'
      registry_address: '""'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: docker_image_build_0
    name: docker镜像构建
    task: docker_image_build@1.6.0
    input:
      image_name: '""'
      image_tag: '"latest"'
      registry_address: '""'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: '"."'
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0

