version: 2
name: 未命名项目
description: ""
global:
  concurrent: 1
trigger:
  webhook: gitlink@1.0.0
  event:
    - ref: create_tag
      ruleset:
        - param-ref: tag
          operator: EQ
          value: '"部署"'
      ruleset-operator: AND
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: end
    name: 结束
    task: end
    needs:
      - shell_0
  - ref: shell_0
    name: shell
    image: docker.jianmuhub.com/library/alpine:3.17.0
    script:
      - ls
    needs:
      - start

